
<section class='contactSection'>
    <h2>Contact</h2>
        <form method="post" class="contactForm">
            <label for="inEmail">Votre Email</label>
            <input type="email" name="email" id="inEmail" required><br>
            <label for="areaMessage">Message</label>
            <textarea name="message" id="areaMessage" required></textarea><br>
            <input class="subForm" type="submit">
        </form>

</section>

