
 <section id="startMain">

    </section>

<section id="index">
   
    
    <section class="main-content">

        
        <section class="dip">
            <h1>Apprenez sans distraction</h1>
            <p>Formez vous avec des videos en ligne en ayant les mains liées !</p> 
        </section>

        
    </section>
    <section id="diaporama">

        <div id="slider">
            <img src="img/diapo1.1.svg" alt="diaporamas d'explication du site" id="slide">   
        </div>
        <div id="commandsSlide">

        <button class="slideBtn" id="previousBtn" ><i class="fas fa-arrow-left"></i></button>

        <button class="slideBtn" id="nextBtn" ><i class="fas fa-arrow-right"></i></button>
        
        </div>

        <img src="img/diapoGif.gif" alt="gif d'explication du site" id="gifExplain">


    </section>
</section>


<script src="<?= $path ?>js/slider.js"></script>