
<?php
if(isset($errorMsg))
{
 foreach($errorMsg as $error)
 {
 ?>
  <div class="notifLog">
   <strong>Attention ! <?php echo $error; ?></strong>
  </div>
    <?php
 }
}

?> 
<!--erreur en js-->

<div id="erreurForm" class='notifLog'></div>


<!--  -->

<form action="../controllers/login.php" method="post">
    <table class="form">
        <tr>
            <td><input class="inputLog usernameField" type="text" name="username" placeholder="Identifiant"></td>
        </tr>
        <tr>
            <td><input class="inputLog passwordField" type="password" name="password" placeholder="Mot de passe"></td>
        </tr>
        <tr>
            <td>
                <input class="btnLog" type="submit" name="login" value="Se connecter">
                <input class="btnLog" type="reset" name="reset" value="Annuler">
            </td>
        </tr>

    </table>
</form>

<script src="../js/validationLogin.js"></script>
